openapi: 3.2.0
info:
  title: Device Reachability Status Subscriptions Device…
  description: This API provides the API consumer with the ability to subscribe to Reachability status events.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.8.0
  x-camara-commonalities: 0.6
servers:
- url: '{apiRoot}/device-reachability-status-subscriptions/v0.8'
  variables:
    apiRoot:
      default: http://localhost:9091
      description: API root, defined by the service provider, e.g. api.example.com or api.example.com/somepath
tags:
- name: Device reachability status subscription
  description: Operation to manage event subscription on device reachability status event.
paths:
  /subscriptions:
    post:
      tags:
      - Device reachability status subscription
      summary: Create a device reachability status event subscription for a device
      operationId: createDeviceReachabilityStatusSubscription
      parameters:
      - $ref: '#/components/parameters/x-correlator'
      security:
      - openId:
        - device-reachability-status-subscriptions:org.camaraproject.device-reachability-status-subscriptions.v0.reachability-data:create
        - device-reachability-status-subscriptions:org.camaraproject.device-reachability-status-subscriptions.v0.reachability-sms:create
        - device-reachability-status-subscriptions:org.camaraproject.device-reachability-status-subscriptions.v0.reachability-disconnected:create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionRequest'
            examples:
              Create Subscription:
                $ref: '#/components/examples/CREATE_SUBSCRIPTION'
      callbacks:
        notifications:
          '{$request.body#/sink}':
            post:
              summary: notifications callback
              description: 'Important: this endpoint is to be implemented by the API consumer.

                The Device status server will call this endpoint whenever any device reachability status related event occurs.

                '
              operationId: postNotification
              parameters:
              - $ref: '#/components/parameters/x-correlator'
              requestBody:
                required: true
                content:
                  application/cloudevents+json:
                    schema:
                      $ref: '#/components/schemas/CloudEvent'
                    examples:
                      reachability-data:
                        $ref: '#/components/examples/REACHABILITY_DATA'
                      reachability-sms:
                        $ref: '#/components/examples/REACHABILITY_SMS'
                      reachability-disconnected:
                        $ref: '#/components/examples/REACHABILITY_DISCONNECTED'
                      subscription-started:
                        $ref: '#/components/examples/SUBSCRIPTION_STARTED'
                      subscription-updated:
                        $ref: '#/components/examples/SUBSCRIPTION_UPDATED'
                      subscription-ended:
                        $ref: '#/components/examples/SUBSCRIPTION_ENDED'
              responses:
                '204':
                  description: Successful notification
                  headers:
                    x-correlator:
                      $ref: '#/components/headers/x-correlator'
                '400':
                  $ref: '#/components/responses/Generic400'
                '401':
                  $ref: '#/components/responses/Generic401'
                '403':
                  $ref: '#/components/responses/Generic403'
                '410':
                  $ref: '#/components/responses/Generic410'
                '429':
                  $ref: '#/components/responses/Generic429'
              security:
              - {}
              - notificationsBearerAuth: []
      responses:
        '201':
          description: Created
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
              examples:
                Active Subscription:
                  $ref: '#/components/examples/ACTIVE_SUBSCRIPTION'
                Active Subscription With Device Disambiguation:
                  $ref: '#/components/examples/ACTIVE_SUBSCRIPTION_WITH_DEVICE_DISAMBIGUATION'
        '202':
          description: Request accepted to be processed. It applies for async creation process.
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionAsync'
        '400':
          $ref: '#/components/responses/CreateSubscriptionBadRequest400'
        '401':
          $ref: '#/components/responses/Generic401'
        '403':
          $ref: '#/components/responses/SubscriptionPermissionDenied403'
        '409':
          $ref: '#/components/responses/Generic409'
        '422':
          $ref: '#/components/responses/CreateSubscriptionUnprocessableEntity422'
        '429':
          $ref: '#/components/responses/Generic429'
    get:
      tags:
      - Device reachability status subscription
      summary: Retrieve a list of device reachability status event subscription
      description: Retrieve a list of device reachability status event subscription(s)
      operationId: retrieveDeviceReachabilityStatusSubscriptionList
      parameters:
      - $ref: '#/components/parameters/x-correlator'
      security:
      - openId:
        - device-reachability-status-subscriptions:read
      responses:
        '200':
          description: List of event subscription details
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
          content:
            application/json:
              schema:
                type: array
                minItems: 0
                items:
                  $ref: '#/components/schemas/Subscription'
              examples:
                List of Subscriptions:
                  $ref: '#/components/examples/SUBSCRIPTION_LIST'
                Empty List of Subscriptions:
                  $ref: '#/components/examples/EMPTY_SUBSCRIPTION_LIST'
        '400':
          $ref: '#/components/responses/Generic400'
        '401':
          $ref: '#/components/responses/Generic401'
        '403':
          $ref: '#/components/responses/Generic403'
  /subscriptions/{subscriptionId}:
    get:
      tags:
      - Device reachability status subscription
      summary: Retrieve a device reachability status event subscription for a device
      operationId: retrieveDeviceReachabilityStatusSubscription
      description: Retrieve a given subscription by ID
      security:
      - openId:
        - device-reachability-status-subscriptions:read
      parameters:
      - $ref: '#/components/parameters/SubscriptionId'
      - $ref: '#/components/parameters/x-correlator'
      responses:
        '200':
          description: OK
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
              examples:
                Active Subscription:
                  $ref: '#/components/examples/ACTIVE_SUBSCRIPTION'
                Active Subscription With Device Disambiguation:
                  $ref: '#/components/examples/ACTIVE_SUBSCRIPTION_WITH_DEVICE_DISAMBIGUATION'
                Subscription Activation Requested:
                  $ref: '#/components/examples/SUBSCRIPTION_ACTIVATION_REQUESTED'
                Subscription Deleted:
                  $ref: '#/components/examples/SUBSCRIPTION_DELETED'
        '400':
          $ref: '#/components/responses/SubscriptionIdRequired400'
        '401':
          $ref: '#/components/responses/Generic401'
        '403':
          $ref: '#/components/responses/Generic403'
        '404':
          $ref: '#/components/responses/Generic404'
    delete:
      tags:
      - Device reachability status subscription
      summary: Delete a device reachability status event subscription for a device
      operationId: deleteDeviceReachabilityStatusSubscription
      description: Delete a given subscription by ID
      security:
      - openId:
        - device-reachability-status-subscriptions:delete
      parameters:
      - $ref: '#/components/parameters/SubscriptionId'
      - $ref: '#/components/parameters/x-correlator'
      responses:
        '204':
          description: event subscription deleted
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
        '202':
          description: Request accepted to be processed. It applies for async deletion process.
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionAsync'
        '400':
          $ref: '#/components/responses/SubscriptionIdRequired400'
        '401':
          $ref: '#/components/responses/Generic401'
        '403':
          $ref: '#/components/responses/Generic403'
        '404':
          $ref: '#/components/responses/Generic404'
components:
  examples:
    CREATE_SUBSCRIPTION:
      value:
        sink: https://endpoint.example.com/sink
        sinkCredential:
          credentialType: ACCESSTOKEN
          accessToken: xxx
          accessTokenExpiresUtc: '2024-02-17T16:23:45Z'
          accessTokenType: bearer
        protocol: HTTP
        types:
        - org.camaraproject.device-reachability-status-subscriptions.v0.reachability-data
        config:
          subscriptionDetail:
            device:
              phoneNumber: '+123456789'
          subscriptionExpireTime: '2023-01-17T13:18:23.682Z'
          subscriptionMaxEvents: 5
          initialEvent: true
    REACHABILITY_DISCONNECTED:
      value:
        id: '123656'
        source: https://notificationSendServer12.supertelco.com
        type: org.camaraproject.device-reachability-status-subscriptions.v0.reachability-disconnected
        specversion: '1.0'
        datacontenttype: application/json
        data:
          device:
            phoneNumber: '+123456789'
          subscriptionId: qs15-h556-rt89-1298
        time: '2023-01-19T13:18:23.682Z'
    SUBSCRIPTION_DELETED:
      value:
        id: 550e8400-e29b-41d4-a716-446655440000
        sink: https://endpoint.example.com/sink
        protocol: HTTP
        types:
        - org.camaraproject.device-reachability-status-subscriptions.v0.reachability-data
        config:
          subscriptionDetail: {}
          subscriptionExpireTime: '2024-07-17T13:18:23.682Z'
          subscriptionMaxEvents: 5
          initialEvent: true
        startsAt: '2024-07-03T21:12:02.871Z'
        expiresAt: '2024-07-03T21:12:02.871Z'
        status: DELETED
    EMPTY_SUBSCRIPTION_LIST:
      description: The API consumer either has no subscriptions or, if a 3-legged access token is used, has none for the device associated with that token.
      value: []
    SUBSCRIPTION_LIST:
      description: A list of API consumer subscriptions. If a 3-legged access token is used, the list is specific to the device associated with that token.
      value:
      - id: 550e8400-e29b-41d4-a716-446655440000
        sink: https://endpoint.example.com/sink
        protocol: HTTP
        types:
        - org.camaraproject.device-reachability-status-subscriptions.v0.reachability-data
        config:
          subscriptionDetail: {}
          subscriptionExpireTime: '2024-07-17T13:18:23.682Z'
          subscriptionMaxEvents: 5
          initialEvent: true
        startsAt: '2024-07-03T21:12:02.871Z'
        expiresAt: '2024-07-03T21:12:02.871Z'
        status: ACTIVE
    ACTIVE_SUBSCRIPTION_WITH_DEVICE_DISAMBIGUATION:
      value:
        id: 550e8400-e29b-41d4-a716-446655440000
        sink: https://endpoint.example.com/sink
        protocol: HTTP
        types:
        - org.camaraproject.device-reachability-status-subscriptions.v0.reachability-data
        config:
          subscriptionDetail:
            device:
              phoneNumber: '+123456789'
          subscriptionExpireTime: '2024-07-17T13:18:23.682Z'
          subscriptionMaxEvents: 5
          initialEvent: true
        startsAt: '2024-07-03T21:12:02.871Z'
        expiresAt: '2024-07-03T21:12:02.871Z'
        status: ACTIVE
    SUBSCRIPTION_ENDED:
      description: The cloud event when a device reachability status subscription ends.
      value:
        id: '123658'
        source: https://notificationSendServer12.supertelco.com
        type: org.camaraproject.device-reachability-status-subscriptions.v0.subscription-ended
        specversion: '1.0'
        datacontenttype: application/json
        data:
          device:
            phoneNumber: '+123456789'
          terminationReason: SUBSCRIPTION_EXPIRED
          subscriptionId: qs15-h556-rt89-1298
          terminationDescription: Subscription expiry time has been reached
        time: '2024-03-22T05:40:23.682Z'
    ACTIVE_SUBSCRIPTION:
      value:
        id: 550e8400-e29b-41d4-a716-446655440000
        sink: https://endpoint.example.com/sink
        protocol: HTTP
        types:
        - org.camaraproject.device-reachability-status-subscriptions.v0.reachability-data
        config:
          subscriptionDetail: {}
          subscriptionExpireTime: '2024-07-17T13:18:23.682Z'
          subscriptionMaxEvents: 5
          initialEvent: true
        startsAt: '2024-07-03T21:12:02.871Z'
        expiresAt: '2024-07-03T21:12:02.871Z'
        status: ACTIVE
    REACHABILITY_SMS:
      value:
        id: '123656'
        source: https://notificationSendServer12.supertelco.com
        type: org.camaraproject.device-reachability-status-subscriptions.v0.reachability-sms
        specversion: '1.0'
        datacontenttype: application/json
        data:
          device:
            phoneNumber: '+123456789'
          subscriptionId: qs15-h556-rt89-1298
        time: '2023-01-19T13:18:23.682Z'
    SUBSCRIPTION_UPDATED:
      description: The cloud event when a device reachability status subscription was updated.
      value:
        id: '124773'
        source: https://notificationSendServer12.supertelco.com
        type: org.camaraproject.device-reachability-status-subscriptions.v0.subscription-updated
        specversion: '1.0'
        datacontenttype: application/json
        data:
          updateReason: SUBSCRIPTION_ACTIVE
          subscriptionId: qs15-h556-rt89-1298
          device:
            phoneNumber: '+123456789'
        time: '2024-03-05T15:00:23.682Z'
    REACHABILITY_DATA:
      value:
        id: '123656'
        source: https://notificationSendServer12.supertelco.com
        type: org.camaraproject.device-reachability-status-subscriptions.v0.reachability-data
        specversion: '1.0'
        datacontenttype: application/json
        data:
          device:
            phoneNumber: '+123456789'
          subscriptionId: qs15-h556-rt89-1298
        time: '2023-01-19T13:18:23.682Z'
    SUBSCRIPTION_STARTED:
      description: The cloud event when a device reachability status subscription was started.
      value:
        id: '124003'
        source: https://notificationSendServer12.supertelco.com
        type: org.camaraproject.device-reachability-status-subscriptions.v0.subscription-started
        specversion: '1.0'
        datacontenttype: application/json
        data:
          initiationReason: SUBSCRIPTION_CREATED
          subscriptionId: qs15-h556-rt89-1298
          device:
            phoneNumber: '+123456789'
        time: '2024-03-05T15:00:23.682Z'
    SUBSCRIPTION_ACTIVATION_REQUESTED:
      value:
        id: 550e8400-e29b-41d4-a716-446655440000
        sink: https://endpoint.example.com/sink
        protocol: HTTP
        types:
        - org.camaraproject.device-reachability-status-subscriptions.v0.reachability-data
        config:
          subscriptionDetail: {}
          subscriptionExpireTime: '2024-07-17T13:18:23.682Z'
          subscriptionMaxEvents: 5
          initialEvent: true
        startsAt: '2024-07-03T21:12:02.871Z'
        expiresAt: '2024-07-03T21:12:02.871Z'
        status: ACTIVATION_REQUESTED
  responses:
    Generic404:
      description: Resource Not Found
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 404
                code:
                  enum:
                  - NOT_FOUND
          examples:
            GENERIC_404_NOT_FOUND:
              description: Resource is not found
              value:
                status: 404
                code: NOT_FOUND
                message: The specified resource is not found.
    Generic410:
      description: Gone
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 410
                code:
                  enum:
                  - GONE
          examples:
            GENERIC_410_GONE:
              description: Use in notifications flow to allow API Consumer to indicate that its callback is no longer available
              value:
                status: 410
                code: GONE
                message: Access to the target resource is no longer available.
    Generic429:
      description: Too Many Requests
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 429
                code:
                  enum:
                  - QUOTA_EXCEEDED
                  - TOO_MANY_REQUESTS
          examples:
            GENERIC_429_QUOTA_EXCEEDED:
              description: Request is rejected due to exceeding a business quota limit
              value:
                status: 429
                code: QUOTA_EXCEEDED
                message: Out of resource quota.
            GENERIC_429_TOO_MANY_REQUESTS:
              description: Access to the API has been temporarily blocked due to rate or spike arrest limits being reached
              value:
                status: 429
                code: TOO_MANY_REQUESTS
                message: Rate limit reached.
    Generic409:
      description: Conflict
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 409
                code:
                  enum:
                  - ABORTED
                  - ALREADY_EXISTS
          examples:
            GENERIC_409_ABORTED:
              description: Concurreny of processes of the same nature/scope
              value:
                status: 409
                code: ABORTED
                message: Concurrency conflict.
            GENERIC_409_ALREADY_EXISTS:
              description: Trying to create an existing resource
              value:
                status: 409
                code: ALREADY_EXISTS
                message: The resource that a client tried to create already exists.
    Generic400:
      description: Problem with the client request
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 400
                code:
                  enum:
                  - INVALID_ARGUMENT
          examples:
            GENERIC_400_INVALID_ARGUMENT:
              description: Invalid Argument. Generic Syntax Exception
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: Client specified an invalid argument, request body or query param.
    SubscriptionIdRequired400:
      description: Problem with the client request
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 400
                code:
                  enum:
                  - INVALID_ARGUMENT
          examples:
            GENERIC_400_INVALID_ARGUMENT:
              description: Invalid Argument. Generic Syntax Exception
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: Client specified an invalid argument, request body or query param.
            GENERIC_400_SUBSCRIPTION_ID_REQUIRED:
              description: subscription id is required
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: 'Expected property is missing: subscriptionId'
    SubscriptionPermissionDenied403:
      description: Client does not have sufficient permission
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 403
                code:
                  enum:
                  - PERMISSION_DENIED
                  - SUBSCRIPTION_MISMATCH
          examples:
            GENERIC_403_PERMISSION_DENIED:
              description: Permission denied. OAuth2 token access does not have the required scope or when the user fails operational security
              value:
                status: 403
                code: PERMISSION_DENIED
                message: Client does not have sufficient permissions to perform this action.
            GENERIC_403_SUBSCRIPTION_MISMATCH:
              description: Inconsistent access token for requested subscription
              value:
                status: 403
                code: SUBSCRIPTION_MISMATCH
                message: Inconsistent access token for requested events subscription
    Generic403:
      description: Client does not have sufficient permission
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 403
                code:
                  enum:
                  - PERMISSION_DENIED
          examples:
            GENERIC_403_PERMISSION_DENIED:
              description: Permission denied. OAuth2 token access does not have the required scope or when the user fails operational security
              value:
                status: 403
                code: PERMISSION_DENIED
                message: Client does not have sufficient permissions to perform this action.
    CreateSubscriptionBadRequest400:
      description: Problem with the client request
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 400
                code:
                  enum:
                  - INVALID_ARGUMENT
                  - OUT_OF_RANGE
                  - INVALID_PROTOCOL
                  - INVALID_CREDENTIAL
                  - INVALID_TOKEN
                  - INVALID_SINK
          examples:
            GENERIC_400_INVALID_ARGUMENT:
              description: Invalid Argument. Generic Syntax Exception
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: Client specified an invalid argument, request body or query param.
            GENERIC_400_OUT_OF_RANGE:
              description: Out of Range. Specific Syntax Exception used when a given field has a pre-defined range or a invalid filter criteria combination is requested
              value:
                status: 400
                code: OUT_OF_RANGE
                message: Client specified an invalid range.
            GENERIC_400_INVALID_PROTOCOL:
              description: Invalid protocol for events subscription management
              value:
                status: 400
                code: INVALID_PROTOCOL
                message: Only HTTP is supported
            GENERIC_400_INVALID_CREDENTIAL:
              description: Invalid sink credential type
              value:
                status: 400
                code: INVALID_CREDENTIAL
                message: Only Access token is supported
            GENERIC_400_INVALID_TOKEN:
              description: Invalid token type for sink credential of type ACCESSTOKEN
              value:
                status: 400
                code: INVALID_TOKEN
                message: Only bearer token is supported
            GENERIC_400_INVALID_SINK:
              description: Invalid sink value
              value:
                status: 400
                code: INVALID_SINK
                message: sink not valid for the specified protocol
    Generic401:
      description: Authentication problem with the client request
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 401
                code:
                  enum:
                  - UNAUTHENTICATED
          examples:
            GENERIC_401_UNAUTHENTICATED:
              description: Request cannot be authenticated and a new authentication is required
              value:
                status: 401
                code: UNAUTHENTICATED
                message: Request not authenticated due to missing, invalid, or expired credentials. A new authentication is required.
    CreateSubscriptionUnprocessableEntity422:
      description: Unprocessable Entity
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 422
                code:
                  enum:
                  - SERVICE_NOT_APPLICABLE
                  - MISSING_IDENTIFIER
                  - UNSUPPORTED_IDENTIFIER
                  - UNNECESSARY_IDENTIFIER
                  - MULTIEVENT_SUBSCRIPTION_NOT_SUPPORTED
          examples:
            GENERIC_422_SERVICE_NOT_APPLICABLE:
              description: Service not applicable for the provided identifier
              value:
                status: 422
                code: SERVICE_NOT_APPLICABLE
                message: The service is not available for the provided identifier.
            GENERIC_422_MISSING_IDENTIFIER:
              description: An identifier is not included in the request and the device or phone number identification cannot be derived from the 3-legged access token
              value:
                status: 422
                code: MISSING_IDENTIFIER
                message: The device cannot be identified.
            GENERIC_422_UNSUPPORTED_IDENTIFIER:
              description: None of the provided identifiers is supported by the implementation
              value:
                status: 422
                code: UNSUPPORTED_IDENTIFIER
                message: The identifier provided is not supported.
            GENERIC_422_UNNECESSARY_IDENTIFIER:
              description: An explicit identifier is provided when a device or phone number has already been identified from the access token
              value:
                status: 422
                code: UNNECESSARY_IDENTIFIER
                message: The device is already identified by the access token.
            GENERIC_422_MULTIEVENT_SUBSCRIPTION_NOT_SUPPORTED:
              description: Multi event types subscription is not supported
              value:
                status: 422
                code: MULTIEVENT_SUBSCRIPTION_NOT_SUPPORTED
                message: Multi event types subscription not managed
  schemas:
    NetworkAccessIdentifier:
      description: A public identifier addressing a subscription in a mobile network. In 3GPP terminology, it corresponds to the GPSI formatted with the External Identifier ({Local Identifier}@{Domain Identifier}). Unlike the telephone number, the network access identifier is not subjected to portability ruling in force, and is individually managed by each operator.
      type: string
      example: 123456789@domain.com
    ErrorInfo:
      type: object
      required:
      - status
      - code
      - message
      properties:
        status:
          type: integer
          description: HTTP response status code
        code:
          type: string
          description: A human-readable code to describe the error
        message:
          type: string
          description: A human-readable description of what the event represents
    Config:
      description: 'Implementation-specific configuration parameters needed by the subscription manager for acquiring events.

        In CAMARA we have predefined attributes like `subscriptionExpireTime`, `subscriptionMaxEvents`, `initialEvent`

        Specific event type attributes must be defined in `subscriptionDetail`

        Note: if a request is performed for several event type, all subscribed event will use same `config` parameters.

        '
      type: object
      required:
      - subscriptionDetail
      properties:
        subscriptionDetail:
          $ref: '#/components/schemas/CreateSubscriptionDetail'
        subscriptionExpireTime:
          type: string
          format: date-time
          example: 2023-01-17 13:18:23.682000+00:00
          description: The subscription expiration time (in date-time format) requested by the API consumer.
        subscriptionMaxEvents:
          type: integer
          description: Identifies the maximum number of event reports to be generated (>=1) requested by the API consumer - Once this number is reached, the subscription ends.
          minimum: 1
          example: 5
        initialEvent:
          type: boolean
          description: 'Set to `true` by API consumer if consumer wants to get an event as soon as the subscription is created and current situation reflects event request.

            Example: Consumer subscribes to reachability SMS. If consumer sets initialEvent to true and device is already reachable by SMS, an event is triggered.

            '
    SubscriptionId:
      type: string
      description: The unique identifier of the subscription in the scope of the subscription manager. When this information is contained within an event notification, this concept SHALL be referred as subscriptionId as per Commonalities Event Notification Model.
      example: qs15-h556-rt89-1298
    Subscription:
      description: Represents a event-type subscription.
      type: object
      required:
      - sink
      - protocol
      - config
      - types
      - id
      properties:
        protocol:
          $ref: '#/components/schemas/Protocol'
        sink:
          type: string
          format: uri
          pattern: ^https:\/\/.+$
          description: The address to which events shall be delivered using the selected protocol.
          example: https://endpoint.example.com/sink
        types:
          description: 'Camara Event types eligible to be delivered by this subscription.

            Note: For the current Commonalities API design guidelines, only one event type per subscription is allowed

            '
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/SubscriptionEventType'
        config:
          $ref: '#/components/schemas/Config'
        id:
          $ref: '#/components/schemas/SubscriptionId'
        startsAt:
          type: string
          format: date-time
          description: 'Date when the event subscription will begin/began

            It must follow [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) and must have time zone.

            Recommended format is yyyy-MM-dd''T''HH:mm:ss.SSSZ (i.e. which allows 2023-07-03T14:27:08.312+02:00 or 2023-07-03T12:27:08.312Z)

            '
          example: '2023-07-03T12:27:08.312Z'
        expiresAt:
          type: string
          format: date-time
          description: 'Date when the event subscription will expire. Only provided when `subscriptionExpireTime` is indicated by API client or Telco Operator has specific policy about that.

            It must follow [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) and must have time zone.

            Recommended format is yyyy-MM-dd''T''HH:mm:ss.SSSZ (i.e. which allows 2023-07-03T14:27:08.312+02:00 or 2023-07-03T12:27:08.312Z)

            '
          example: '2023-07-03T12:27:08.312Z'
        status:
          type: string
          description: "Current status of the subscription - Management of Subscription State engine is not mandatory for now. Note not all statuses may be considered to be implemented. Details:\n  - `ACTIVATION_REQUESTED`: Subscription creation (POST) is triggered but subscription creation process is not finished yet.\n  - `ACTIVE`: Subscription creation process is completed. Subscription is fully operative.\n  - `INACTIVE`: Subscription is temporarily inactive, but its workflow logic is not deleted.\n  - `EXPIRED`: Subscription is ended (no longer active). This status applies when subscription is ended due to `SUBSCRIPTION_EXPIRED` or `ACCESS_TOKEN_EXPIRED` event.\n  - `DELETED`: Subscription is ended as deleted (no longer active). This status applies when subscription information is kept (i.e. subscription workflow is no longer active but its meta-information is kept)."
          enum:
          - ACTIVATION_REQUESTED
          - ACTIVE
          - EXPIRED
          - INACTIVE
          - DELETED
      discriminator:
        propertyName: protocol
        mapping:
          HTTP: '#/components/schemas/HTTPSubscriptionResponse'
          MQTT3: '#/components/schemas/MQTTSubscriptionResponse'
          MQTT5: '#/components/schemas/MQTTSubscriptionResponse'
          AMQP: '#/components/schemas/AMQPSubscriptionResponse'
          NATS: '#/components/schemas/NATSSubscriptionResponse'
          KAFKA: '#/components/schemas/ApacheKafkaSubscriptionResponse'
      example:
        id: 550e8400-e29b-41d4-a716-446655440000
        sink: https://endpoint.example.com/sink
        protocol: HTTP
        types:
        - org.camaraproject.device-reachability-status-subscriptions.v0.reachability-data
        config:
          subscriptionDetail:
            device:
              phoneNumber: '+123456789'
          subscriptionExpireTime: '2024-07-17T13:18:23.682Z'
          subscriptionMaxEvents: 5
          initialEvent: true
        startsAt: '2024-07-03T21:12:02.871Z'
        expiresAt: '2024-07-03T21:12:02.871Z'
        status: ACTIVE
    DeviceIpv6Address:
      description: 'The device should be identified by the observed IPv6 address, or by any single IPv6 address from within the subnet allocated to the device (e.g. adding ::0 to the /64 prefix).

        '
      type: string
      format: ipv6
      example: 2001:db8:85a3:8d3:1319:8a2e:370:7344
    DeviceIpv4Addr:
      type: object
      description: 'The device should be identified by either the public (observed) IP address and port as seen by the application server, or the private (local) and any public (observed) IP addresses in use by the device (this information can be obtained by various means, for example from some DNS servers).


        If the allocated and observed IP addresses are the same (i.e. NAT is not in use) then  the same address should be specified for both publicAddress and privateAddress.


        If NAT64 is in use, the device should be identified by its publicAddress and publicPort, or separately by its allocated IPv6 address (field ipv6Address of the Device object)


        In all cases, publicAddress must be specified, along with at least one of either privateAddress or publicPort, dependent upon which is known. In general, mobile devices cannot be identified by their public IPv4 address alone.

        '
      properties:
        publicAddress:
          $ref: '#/components/schemas/SingleIpv4Addr'
        privateAddress:
          $ref: '#/components/schemas/SingleIpv4Addr'
        publicPort:
          $ref: '#/components/schemas/Port'
      anyOf:
      - required:
        - publicAddress
        - privateAddress
      - required:
        - publicAddress
        - publicPort
      example:
        publicAddress: 84.125.93.10
        publicPort: 59765
    SubscriptionEventType:
      type: string
      description: 'reachability-data - Event triggered when the device is connected to the network for Data usage (regardless of the SMS reachability).


        reachability-sms - Event triggered when the device is connected to the network only for SMS usage


        reachability-disconnected - Event triggered when the device is not connected.

        '
      enum:
      - org.camaraproject.device-reachability-status-subscriptions.v0.reachability-data
      - org.camaraproject.device-reachability-status-subscriptions.v0.reachability-sms
      - org.camaraproject.device-reachability-status-subscriptions.v0.reachability-disconnected
    SubscriptionAsync:
      description: Response for a device reachability status operation managed asynchronously (Creation or Deletion)
      type: object
      required:
      - id
      properties:
        id:
          $ref: '#/components/schemas/SubscriptionId'
    EventTypeNotification:
      type: string
      description: 'reachability-data - Event triggered when the device is connected to the network for Data usage (regardless of the SMS reachability).


        reachability-sms - Event triggered when the device is connected to the network only for SMS usage.


        reachability-disconnected - Event triggered when the device is not connected.


        subscription-started - Event triggered when the subscription starts.


        subscription-updated - Event triggered when the subscription is updated.


        subscription-ended - Event triggered when the subscription ends.

        '
      enum:
      - org.camaraproject.device-reachability-status-subscriptions.v0.reachability-data
      - org.camaraproject.device-reachability-status-subscriptions.v0.reachability-sms
      - org.camaraproject.device-reachability-status-subscriptions.v0.reachability-disconnected
      - org.camaraproject.device-reachability-status-subscriptions.v0.subscription-started
      - org.camaraproject.device-reachability-status-subscriptions.v0.subscription-updated
      - org.camaraproject.device-reachability-status-subscriptions.v0.subscription-ended
    XCorrelator:
      type: string
      pattern: ^[a-zA-Z0-9-_:;.\/<>{}]{0,256}$
      example: b4333c46-49c0-4f62-80d7-f0ef930f1c46
    PhoneNumber:
      description: A public identifier addressing a telephone subscription. In mobile networks it corresponds to the MSISDN (Mobile Station International Subscriber Directory Number). In order to be globally unique it has to be formatted in international format, according to E.164 standard, prefixed with '+'.
      type: string
      pattern: ^\+[1-9][0-9]{4,14}$
      example: '+123456789'
    CreateSubscriptionDetail:
      description: The detail of the requested event subscription.
      type: object
      properties:
        device:
          $ref: '#/components/schemas/Device'
    Protocol:
      type: string
      enum:
      - HTTP
      - MQTT3
      - MQTT5
      - AMQP
      - NATS
      - KAFKA
      description: Identifier of a delivery protocol. Only HTTP is allowed for now
      example: HTTP
    DateTime:
      type: string
      format: date-time
      description: 'Timestamp of when the occurrence happened.

        If the time of the occurrence cannot be determined then this attribute MAY be set to some other time (such as the current time) by the CloudEvents producer,

        however all producers for the same source MUST be consistent in this respect. In other words,

        either they all use the actual time of the occurrence or they all use the same algorithm to determine the value used.

        It must follow [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) and must have time zone.

        Recommended format is yyyy-MM-dd''T''HH:mm:ss.SSSZ (i.e. which allows 2023-07-03T14:27:08.312+02:00 or 2023-07-03T12:27:08.312Z)

        '
      example: '2018-04-05T17:31:00Z'
    SingleIpv4Addr:
      description: A single IPv4 address with no subnet mask
      type: string
      format: ipv4
      example: 84.125.93.10
    SinkCredential:
      description: A sink credential provides authentication or authorization information necessary to enable delivery of events to a target.
      type: object
      properties:
        credentialType:
          type: string
          enum:
          - PLAIN
          - ACCESSTOKEN
          - REFRESHTOKEN
          description: 'The type of the credential.

            Note: Type of the credential - MUST be set to ACCESSTOKEN for now

            '
      discriminator:
        propertyName: credentialType
        mapping:
          PLAIN: '#/components/schemas/PlainCredential'
          ACCESSTOKEN: '#/components/schemas/AccessTokenCredential'
          REFRESHTOKEN: '#/components/schemas/RefreshTokenCredential'
      required:
      - credentialType
    Port:
      description: TCP or UDP port number
      type: integer
      minimum: 0
      maximum: 65535
    Source:
      type: string
      format: uri-reference
      minLength: 1
      description: "Identifies the context in which an event happened - be a non-empty `URI-reference` like:\n- URI with a DNS authority:\n  * https://github.com/cloudevents\n  * mailto:cncf-wg-serverless@lists.cncf.io\n- Universally-unique URN with a UUID:\n  * urn:uuid:6e8bc430-9c3a-11d9-9669-0800200c9a66\n- Application-specific identifier:\n  * /cloudevents/spec/pull/123\n  * 1-555-123-4567\n"
      example: https://notificationSendServer12.supertelco.com
    CloudEvent:
      description: The notification callback
      required:
      - id
      - source
      - specversion
      - type
      - time
      properties:
        id:
          type: string
          description: identifier of this event, that must be unique in the source context.
        source:
          $ref: '#/components/schemas/Source'
        type:
          $ref: '#/components/schemas/EventTypeNotification'
        specversion:
          type: string
          description: Version of the specification to which this event conforms (must be 1.0 if it conforms to cloudevents 1.0.2 version)
          enum:
          - '1.0'
        datacontenttype:
          type: string
          description: media-type that describes the event payload encoding, must be "application/json" for CAMARA APIs
          enum:
          - application/json
        data:
          type: object
          description: Event details payload described in each CAMARA API and referenced by its type
        time:
          $ref: '#/components/schemas/DateTime'
      discriminator:
        propertyName: type
        mapping:
          org.camaraproject.device-reachability-status-subscriptions.v0.reachability-data: '#/components/schemas/EventReachabilityData'
          org.camaraproject.device-reachability-status-subscriptions.v0.reachability-sms: '#/components/schemas/EventReachabilitySms'
          org.camaraproject.device-reachability-status-subscriptions.v0.reachability-disconnected: '#/components/schemas/EventReachabilityDisconnected'
          org.camaraproject.device-reachability-status-subscriptions.v0.subscription-started: '#/components/schemas/EventSubscriptionStarted'
          org.camaraproject.device-reachability-status-subscriptions.v0.subscription-updated: '#/components/schemas/EventSubscriptionUpdated'
          org.camaraproject.device-reachability-status-subscriptions.v0.subscription-ended: '#/components/schemas/EventSubscriptionEnded'
    SubscriptionRequest:
      description: The request for creating a event-type event subscription
      type: object
      required:
      - sink
      - protocol
      - config
      - types
      properties:
        protocol:
          $ref: '#/components/schemas/Protocol'
        sink:
          type: string
          format: uri
          pattern: ^https:\/\/.+$
          description: The address to which events shall be delivered using the selected protocol.
          example: https://endpoint.example.com/sink
        sinkCredential:
          $ref: '#/components/schemas/SinkCredential'
        types:
          description: 'Camara Event types eligible to be delivered by this subscription.

            Note: For the current Commonalities API design guidelines, only one event type per subscription is allowed, yet in the following releases use of array of event types SHALL be specified without changing this definition.

            '
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/SubscriptionEventType'
        config:
          $ref: '#/components/schemas/Config'
      discriminator:
        propertyName: protocol
        mapping:
          HTTP: '#/components/schemas/HTTPSubscriptionRequest'
          MQTT3: '#/components/schemas/MQTTSubscriptionRequest'
          MQTT5: '#/components/schemas/MQTTSubscriptionRequest'
          AMQP: '#/components/schemas/AMQPSubscriptionRequest'
          NATS: '#/components/schemas/NATSSubscriptionRequest'
          KAFKA: '#/components/schemas/ApacheKafkaSubscriptionRequest'
    Device:
      description: 'End-user equipment able to connect to a mobile network. Examples of devices include smartphones or IoT sensors/actuators.


        The developer can choose to provide the below specified device identifiers:


        * `ipv4Address`

        * `ipv6Address`

        * `phoneNumber`

        * `networkAccessIdentifier`


        NOTE: the MNO might support only a subset of these options. The API invoker can provide multiple identifiers to be compatible across different MNOs. In this case the identifiers MUST belong to the same device.

        '
      type: object
      properties:
        phoneNumber:
          $ref: '#/components/schemas/PhoneNumber'
        networkAccessIdentifier:
          $ref: '#/components/schemas/NetworkAccessIdentifier'
        ipv4Address:
          $ref: '#/components/schemas/DeviceIpv4Addr'
        ipv6Address:
          $ref: '#/components/schemas/DeviceIpv6Address'
      minProperties: 1
  parameters:
    SubscriptionId:
      name: subscriptionId
      in: path
      description: Subscription identifier that was obtained from the create event subscription operation
      required: true
      schema:
        $ref: '#/components/schemas/SubscriptionId'
    x-correlator:
      name: x-correlator
      in: header
      description: Correlation id for the different services
      schema:
        $ref: '#/components/schemas/XCorrelator'
  headers:
    x-correlator:
      description: Correlation id for the different services
      schema:
        $ref: '#/components/schemas/XCorrelator'
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
    notificationsBearerAuth:
      type: http
      scheme: bearer
      bearerFormat: '{$request.body#/sinkCredential.credentialType}'
externalDocs:
  description: Product documentation at CAMARA
  url: https://github.com/camaraproject/DeviceReachabilityStatus
