openapi: 3.2.0
info:
  description: 'Service Enabling Payments against Operator Carrier Billing Systems


    # Introduction


    The Carrier Billing API provides programmable interface for developers and other users (capabilities consumers) to charge an amount on a mobile line.'
  version: 0.5.0
  title: Carrier Billing One Step Payment API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-camara-commonalities: 0.6
servers:
- url: '{apiRoot}/carrier-billing/v0.5'
  variables:
    apiRoot:
      default: http://localhost:9091
      description: API root, defined by the service provider
tags:
- name: One Step Payment
  description: Operations to manage One Step Payment procedure
paths:
  /payments:
    post:
      security:
      - openId:
        - carrier-billing:payments:create
      tags:
      - One Step Payment
      summary: Create a new Payment
      operationId: createPayment
      description: Create a new payment for subsequent charging to an end user. Carrier Billing Server will apply the charging according to business configuration for the end user.
      parameters:
      - $ref: '#/components/parameters/x-correlator'
      requestBody:
        description: Amount transaction
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePayment'
        required: true
      callbacks:
        notifications:
          '{$request.body#/sink}':
            post:
              security:
              - {}
              - notificationsBearerAuth: []
              tags:
              - Payment Notifications
              summary: Carrier Billing payment notifications
              operationId: createPaymentNotification
              description: 'Important: This endpoint is exposed by the API client, accepting requests in the defined format.

                The Carrier Billing server will call this endpoint whenever any carrier billing related event occurs.

                '
              parameters:
              - $ref: '#/components/parameters/x-correlator'
              requestBody:
                description: Creates a new carrier billing payment notification
                content:
                  application/cloudevents+json:
                    schema:
                      $ref: '#/components/schemas/CloudEvent'
                required: true
              responses:
                '204':
                  description: Successful notification
                  headers:
                    x-correlator:
                      $ref: '#/components/headers/x-correlator'
                '400':
                  $ref: '#/components/responses/Generic400'
                '401':
                  $ref: '#/components/responses/Generic401'
                '403':
                  $ref: '#/components/responses/Generic403'
                '410':
                  $ref: '#/components/responses/Generic410'
                '429':
                  $ref: '#/components/responses/Generic429'
      responses:
        '201':
          description: Created
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentCreated'
        '400':
          $ref: '#/components/responses/PaymentInvalid400'
        '401':
          $ref: '#/components/responses/Generic401'
        '403':
          $ref: '#/components/responses/PaymentPermissionDenied403'
        '404':
          $ref: '#/components/responses/IdentifierNotFound404'
        '409':
          $ref: '#/components/responses/Generic409'
        '422':
          $ref: '#/components/responses/PaymentUnprocessable422'
        '429':
          $ref: '#/components/responses/Generic429'
components:
  schemas:
    ChargingInformation:
      type: object
      required:
      - amount
      - currency
      - description
      properties:
        amount:
          type: number
          format: float
          multipleOf: 0.001
          minimum: 0.001
          description: Amount to be charged or reserved.
          example: 100
        currency:
          type: string
          description: Currency code in which amount is expressed as defined in [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html).
          example: EUR
        description:
          type: string
          description: Description text to be used for information and billing text
          example: FIFA EA Sports 24
        isTaxIncluded:
          type: boolean
          default: false
          description: If true, the `amount` is tax included, if false the `amount` is provided without tax. In both cases, `taxAmount` could be indicated to provide tax amount.
        taxAmount:
          type: number
          format: float
          multipleOf: 0.001
          minimum: 0
          description: 'The tax amount charged by the merchant. Indicated when the merchant is the one applying taxes. This field also provides an indicator to the downstream billing system.

            '
          example: 21
    CreatePayment:
      type: object
      required:
      - amountTransaction
      properties:
        amountTransaction:
          $ref: '#/components/schemas/AmountTransactionInput'
        sink:
          type: string
          format: uri
          pattern: ^https:\/\/.+$
          description: The address to which events shall be delivered, using the HTTP protocol.
          example: https://endpoint.example.com/sink
        sinkCredential:
          allOf:
          - description: A sink credential provides authentication or authorization information necessary to enable delivery of events to a target.
          - $ref: '#/components/schemas/SinkCredential'
    ErrorInfo:
      type: object
      required:
      - status
      - code
      - message
      properties:
        status:
          type: integer
          description: HTTP response status code
        code:
          type: string
          description: A human-readable code to describe the error
        message:
          type: string
          description: A human-readable description of what the event represents
    AmountTransactionInput:
      type: object
      required:
      - paymentAmount
      - referenceCode
      properties:
        phoneNumber:
          type: string
          description: 'Identifies the mobile account to be charged.


            A public identifier addressing a telephone subscription. In mobile networks it corresponds to the MSISDN (Mobile Station International Subscriber Directory Number). In order to be globally unique it has to be formatted in international format, according to E.164 standard, prefixed with ''+''.


            Additional Considerations:

            - Take a look to section `# Identifying the phone number from the access token` regarding the use of this field.'
          pattern: ^\+[1-9][0-9]{4,14}$
          example: '+34671999000'
        clientCorrelator:
          type: string
          description: Uniquely identifies this create payment request. If there is a communication failure during the payment request, using the same clientCorrelator when retrying the request allows the operator to avoid applying the same charge twice. This field SHOULD be present.
          example: req-12f2pgh448gh2hvrfrv
        paymentAmount:
          $ref: '#/components/schemas/PaymentAmountForCharge'
        referenceCode:
          type: string
          description: Merchant generated payment reference to uniquely identify the request, for instance, in the case of disputes.
          example: ref-pay-834tfr2rA3v8r8vr3rv
    PaymentDetails:
      type: array
      description: Detailed description of the concepts/items considered within a specific payment procedure.
      minItems: 1
      items:
        $ref: '#/components/schemas/PaymentItem'
    PaymentItem:
      type: object
      required:
      - id
      - amount
      - currency
      - description
      properties:
        id:
          type: string
          description: Unique payment item identifier. Relevant to uniquely identify an item within a given payment when `paymentDetails` are provided and also to correlate information when a refund regarding this item is performed, by means of using `refundDetails`.
          example: 3goug3uvu32v3b
        amount:
          type: number
          format: float
          multipleOf: 0.001
          minimum: 0.001
          description: Specific amount to be charged or reserved referred to a specific item.
          example: 100
        currency:
          type: string
          description: Currency code in which amount is expressed as defined in [ISO 4217](https://www.iso.org/iso-4217-currency-codes.html).
          example: EUR
        description:
          type: string
          description: Description text to be used for information and billing text referred to a specific item.
          example: FIFA EA Sports 24
        isTaxIncluded:
          type: boolean
          default: false
          description: If true, the `amount` is tax included, if false the `amount` is provided without tax. In both cases, `taxAmount` could be indicated to provide tax amount.
        taxAmount:
          type: number
          format: float
          multipleOf: 0.001
          minimum: 0
          description: 'The tax amount charged by the merchant. Indicated when the merchant is the one applying taxes. This field also provides an indicator to the downstream billing system.

            '
          example: 21
    PaymentCreated:
      type: object
      required:
      - amountTransaction
      - paymentId
      - paymentStatus
      - paymentCreationDate
      properties:
        paymentId:
          type: string
          description: Unique Identifier of the payment
          example: AK234rfweSBuWGFUEWFGWEVWRV
        amountTransaction:
          $ref: '#/components/schemas/AmountTransaction'
        paymentStatus:
          type: string
          description: Specifies the payment status (`processing`, `pending_validation`, `denied`, `reserved`, `succeeded`, `cancelled`).
          example: processing
        paymentCreationDate:
          type: string
          format: date-time
          description: Date time when the payment is created in server database. This is a technical information. It must follow [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) and must have time zone.
        paymentDate:
          type: string
          format: date-time
          description: Date time when the payment is effectively performed. This is a business information. It must follow [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) and must have time zone.
        sink:
          type: string
          format: uri
          pattern: ^https:\/\/.+$
          description: The address to which events shall be delivered, using the HTTP protocol.
          example: https://endpoint.example.com/sink
    XCorrelator:
      type: string
      pattern: ^[a-zA-Z0-9-_:;.\/<>{}]{0,256}$
      example: b4333c46-49c0-4f62-80d7-f0ef930f1c46
    AmountTransaction:
      required:
      - phoneNumber
      - paymentAmount
      - referenceCode
      type: object
      properties:
        phoneNumber:
          type: string
          description: 'Identifies the mobile account to be charged.


            A public identifier addressing a telephone subscription. In mobile networks it corresponds to the MSISDN (Mobile Station International Subscriber Directory Number). In order to be globally unique it has to be formatted in international format, according to E.164 standard, prefixed with ''+''.'
          pattern: ^\+[1-9][0-9]{4,14}$
          example: '+34671999000'
        clientCorrelator:
          type: string
          description: Uniquely identifies this create payment request. If there is a communication failure during the payment request, using the same clientCorrelator when retrying the request allows the operator to avoid applying the same charge twice. This field SHOULD be present. Same value as indicated in the request.
          example: req-12f2pgh448gh2hvrfrv
        paymentAmount:
          $ref: '#/components/schemas/PaymentAmountForCharge'
        referenceCode:
          type: string
          description: Merchant generated payment reference to uniquely identify the request, for instance, in the case of disputes. Same value as the one provided in the request.
          example: ref-pay-834tfr2rA3v8r8vr3rv
        resourceURL:
          type: string
          description: URI of the created resource (same as in the Location header)
          example: urn:payments:AK234rfweSBuWGFUEWFGWEVWRV
        serverReferenceCode:
          type: string
          description: Reference to the charge or refund, provided by the server, and meaningful to the server’s backend system for the purpose of reconciliation.
          example: ref-pay-834tfr2rA3v8r8vr3rv-serv
    DateTime:
      type: string
      format: date-time
      description: Timestamp when the occurrence happened. It must follow [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) and must have time zone.
      example: '2023-11-03T12:27:10Z'
    SinkCredential:
      type: object
      properties:
        credentialType:
          type: string
          enum:
          - PLAIN
          - ACCESSTOKEN
          - REFRESHTOKEN
          description: The type of the credential. Only `ACCESSTOKEN` is supported so far.
      discriminator:
        propertyName: credentialType
        mapping:
          PLAIN: '#/components/schemas/PlainCredential'
          ACCESSTOKEN: '#/components/schemas/AccessTokenCredential'
          REFRESHTOKEN: '#/components/schemas/RefreshTokenCredential'
      required:
      - credentialType
    Source:
      type: string
      format: uri-reference
      minLength: 1
      description: "Identifies the context in which an event happened - be a non-empty `URI-reference` like:\n- URI with a DNS authority:\n  * https://github.com/cloudevents\n  * mailto:cncf-wg-serverless@lists.cncf.io\n- Universally-unique URN with a UUID:\n  * urn:uuid:6e8bc430-9c3a-11d9-9669-0800200c9a66\n- Application-specific identifier:\n  * /cloudevents/spec/pull/123\n  * 1-555-123-4567"
      example: https://notificationSendServer12.supertelco.com
    CloudEvent:
      description: The notification format
      required:
      - id
      - source
      - specversion
      - type
      - time
      properties:
        id:
          type: string
          description: Identifier of this event, that must be unique in the source context.
          minLength: 1
          example: sd5e-uy52-88t4-za66
        source:
          $ref: '#/components/schemas/Source'
        type:
          type: string
          description: Type of event as defined in each CAMARA API
          minLength: 25
          example: org.camaraproject.carrier-billing.v0.payment-reserved
        specversion:
          type: string
          description: Version of the specification to which this event conforms (must be 1.0 if it conforms to cloudevents 1.0.2 version)
          minLength: 3
          example: '1.0'
        datacontenttype:
          type: string
          description: media-type that describes the event payload encoding, must be "application/json" for CAMARA APIs
          example: application/json
        data:
          type: object
          description: Event details payload described in each CAMARA API and referenced by its type
        time:
          $ref: '#/components/schemas/DateTime'
      discriminator:
        propertyName: type
        mapping:
          org.camaraproject.carrier-billing.v0.payment-pending-validation: '#/components/schemas/EventPaymentPendingValidation'
          org.camaraproject.carrier-billing.v0.payment-reserved: '#/components/schemas/EventPaymentReserved'
          org.camaraproject.carrier-billing.v0.payment-completed: '#/components/schemas/EventPaymentCompleted'
          org.camaraproject.carrier-billing.v0.payment-cancelled: '#/components/schemas/EventPaymentCancelled'
          org.camaraproject.carrier-billing.v0.payment-denied: '#/components/schemas/EventPaymentDenied'
    ChargingMetaData:
      type: object
      properties:
        merchantName:
          type: string
          description: Indicates the merchant name. Allows aggregators/partners to specify the actual merchant name
          example: EA Sports
        merchantIdentifier:
          type: string
          description: Indicates the merchant identifier. Allows aggregators/partners to specify the actual merchant identifier
          example: eas-12345
        fee:
          type: number
          format: float
          multipleOf: 0.01
          description: Percentage of the amount to be received by the requester
          example: 10
        purchaseCategoryCode:
          type: string
          description: A category defining the type of service, product or media being purchased
          example: games
        channel:
          type: string
          description: The channel over which the requester is interacting with the merchant (e.g. WAP, Web, SMS...)
          example: web
        serviceId:
          type: string
          description: The identifier of the partner/merchant service being purchased
          example: games-online
        productId:
          type: string
          description: The product identifier to be combined with the `serviceId` to uniquely identify the product being purchased. For example if the `serviceId` relates to a VOD service, the `productId` can specify the movie rented
          example: '138235321'
    PaymentAmountForCharge:
      type: object
      required:
      - chargingInformation
      properties:
        chargingInformation:
          $ref: '#/components/schemas/ChargingInformation'
        chargingMetaData:
          $ref: '#/components/schemas/ChargingMetaData'
        paymentDetails:
          $ref: '#/components/schemas/PaymentDetails'
  responses:
    PaymentUnprocessable422:
      description: "Client indicates content that is understable by the Server but unable to be processed.\nScenarios that may exist:\n  - Service not applicable for the provided identifier (\"code\": \"SERVICE_NOT_APPLICABLE\",\"message\": \"The service is not available for the provided identifier.\")\n  - An identifier is not included in the request and the device or phone number identification cannot be derived from the 3-legged access token (\"code\": \"MISSING_IDENTIFIER\",\"message\": \"The phone number cannot be identified.\")\n  - An explicit identifier is provided when a device or phone number has already been identified from the access token (\"code\": \"UNNECESSARY_IDENTIFIER\",\"message\": \"The phone number is already identified by the access token.\")\n  - Unauthorized amount requested (\"code\": \"CARRIER_BILLING.UNAUTHORIZED_AMOUNT\",\"message\": \"Unauthorized amount requested.\").\n  - Accumulated threshold amount for the user's mobile account overpassed (\"code\": \"CARRIER_BILLING.USER_AMOUNT_THRESHOLD_OVERPASSED\",\"message\": \"Unauthorized payment request. Accumulated user mobile payments overpass account amount threshold.\")."
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 422
                code:
                  enum:
                  - SERVICE_NOT_APPLICABLE
                  - MISSING_IDENTIFIER
                  - UNNECESSARY_IDENTIFIER
                  - CARRIER_BILLING.UNAUTHORIZED_AMOUNT
                  - CARRIER_BILLING.USER_AMOUNT_THRESHOLD_OVERPASSED
          examples:
            GENERIC_422_SERVICE_NOT_APPLICABLE:
              description: Service not applicable for the provided identifier
              value:
                status: 422
                code: SERVICE_NOT_APPLICABLE
                message: The service is not available for the provided identifier.
            GENERIC_422_MISSING_IDENTIFIER:
              description: An identifier is not included in the request and the device or phone number identification cannot be derived from the 3-legged access token
              value:
                status: 422
                code: MISSING_IDENTIFIER
                message: The phone number cannot be identified.
            GENERIC_422_UNNECESSARY_IDENTIFIER:
              description: An explicit identifier is provided when a device or phone number has already been identified from the access token
              value:
                status: 422
                code: UNNECESSARY_IDENTIFIER
                message: The phone number is already identified by the access token.
            GENERIC_422_UNAUTHORIZED_AMOUNT:
              summary: Generic Unauthorized Amount
              description: Unauthorized amount requested
              value:
                status: 422
                code: CARRIER_BILLING.UNAUTHORIZED_AMOUNT
                message: Unauthorized amount requested.
            GENERIC_422_USER_MOBILE_ACCUMULATED_THRESHOLD_AMOUNT_OVERPASSED:
              summary: Generic User Mobile Accumulated threshold Amount Overpassed
              description: Accumulated threshold amount for the user's mobile account overpassed
              value:
                status: 422
                code: CARRIER_BILLING.USER_AMOUNT_THRESHOLD_OVERPASSED
                message: Unauthorized payment request. Accumulated user mobile payments overpass account amount threshold.
    Generic410:
      description: Gone
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 410
                code:
                  enum:
                  - GONE
          examples:
            GENERIC_410_GONE:
              summary: Generic Gone
              description: Use in notifications flow to allow API Consumer to indicate that its callback is no longer available
              value:
                status: 410
                code: GONE
                message: Access to the target resource is no longer available.
    Generic429:
      description: Too Many Requests
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 429
                code:
                  enum:
                  - TOO_MANY_REQUESTS
          examples:
            GENERIC_429_TOO_MANY_REQUESTS:
              summary: Generic Too Many Requests
              description: Access to the API has been temporarily blocked due to rate or spike arrest limits being reached
              value:
                status: 429
                code: TOO_MANY_REQUESTS
                message: Rate limit reached.
    Generic409:
      description: Conflict
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 409
                code:
                  enum:
                  - ALREADY_EXISTS
          examples:
            GENERIC_409_ALREADY_EXISTS:
              summary: Generic Already Exists
              description: Trying to create an existing resource
              value:
                status: 409
                code: ALREADY_EXISTS
                message: The resource that a client tried to create already exists.
    Generic400:
      description: Bad Request
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 400
                code:
                  enum:
                  - INVALID_ARGUMENT
          examples:
            GENERIC_400_INVALID_ARGUMENT:
              summary: Generic Invalid Argument
              description: Invalid Argument. Generic Syntax Exception
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: Client specified an invalid argument, request body or query param.
    IdentifierNotFound404:
      description: Phone Number Not Found
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 404
                code:
                  enum:
                  - IDENTIFIER_NOT_FOUND
          examples:
            GENERIC_404_IDENTIFIER_NOT_FOUND:
              description: Some identifier cannot be matched to a device. In this API it refers to a phoneNumber.
              value:
                status: 404
                code: IDENTIFIER_NOT_FOUND
                message: phoneNumber not found.
    PaymentInvalid400:
      description: "Invalid input.\nCommon INVALID_ARGUMENT scenarios usually are:\n  - Schema validation failed (\"code\": \"INVALID_ARGUMENT\",\"message\": \"Client specified an invalid argument, request body or query param.\").\n  - Currency is unknown or not authorized (\"code\": \"INVALID_ARGUMENT\",\"message\": \"Currency is unknown or not authorized\").\n  - clientCorrelator still exist (\"code\": \"INVALID_ARGUMENT\",\"message\": \"clientCorrelator already exist on server\").\n\nIn addition to regular INVALID_ARGUMENT scenario other scenarios may exist:\n  - Invalid sink credential (\"code\": \"INVALID_CREDENTIAL\",\"message\": \"Only Access token is supported\").\n  - Invalid sink credential access token (\"code\": \"INVALID_TOKEN\",\"message\": \"Only bearer token is supported\").\n  - Invalid sink (\"code\": \"INVALID_SINK\",\"message\": \"sink not valid for the specified protocol\")."
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 400
                code:
                  enum:
                  - INVALID_ARGUMENT
                  - INVALID_CREDENTIAL
                  - INVALID_TOKEN
                  - INVALID_SINK
          examples:
            GENERIC_400_INVALID_ARGUMENT:
              summary: Generic Invalid Argument
              description: Invalid Argument. Generic Syntax Exception
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: Client specified an invalid argument, request body or query param.
            GENERIC_400_WRONG_CURRENCY:
              summary: Generic Wrong Currency
              description: Currency is unknown or not authorized
              value:
                code: INVALID_ARGUMENT
                status: 400
                message: Currency is unknown or not authorized.
            GENERIC_400_DUPLICATE_CLIENT_CORRELATOR:
              summary: Generic Duplicate Client Correlator
              description: clientCorrelator still exist
              value:
                code: INVALID_ARGUMENT
                status: 400
                message: clientCorrelator already exist on server.
            GENERIC_400_INVALID_CREDENTIAL:
              summary: Generic Invalid Credential
              description: Invalid sink credential
              value:
                status: 400
                code: INVALID_CREDENTIAL
                message: Only Access token is supported
            GENERIC_400_INVALID_TOKEN:
              summary: Generic Invalid Token
              description: Invalid sink credential access token
              value:
                status: 400
                code: INVALID_TOKEN
                message: Only bearer token is supported
            GENERIC_400_INVALID_SINK:
              summary: Generic Invalid Sink
              description: Invalid sink value
              value:
                status: 400
                code: INVALID_SINK
                message: sink not valid for the specified protocol
    Generic403:
      description: Forbidden
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 403
                code:
                  enum:
                  - PERMISSION_DENIED
          examples:
            GENERIC_403_PERMISSION_DENIED:
              description: Permission denied. OAuth2 token access does not have the required scope or when the user fails operational security
              value:
                status: 403
                code: PERMISSION_DENIED
                message: Client does not have sufficient permissions to perform this action.
    PaymentPermissionDenied403:
      description: "Client does not have sufficient permission.\nIn addition to regular PERMISSION_DENIED scenario other scenarios may exist:\n  - Payment denied by business (\"code\": \"CARRIER_BILLING.PAYMENT_DENIED\",\"message\": \"Payment denied by business.\")."
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 403
                code:
                  enum:
                  - PERMISSION_DENIED
                  - CARRIER_BILLING.PAYMENT_DENIED
          examples:
            GENERIC_403_PERMISSION_DENIED:
              description: Permission denied. OAuth2 token access does not have the required scope or when the user fails operational security
              value:
                status: 403
                code: PERMISSION_DENIED
                message: Client does not have sufficient permissions to perform this action.
            GENERIC_403_PAYMENT_DENIED:
              summary: Generic Payment Denied
              description: Payment denied by business
              value:
                status: 403
                code: CARRIER_BILLING.PAYMENT_DENIED
                message: Payment denied by business.
    Generic401:
      description: Unauthorized
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 401
                code:
                  enum:
                  - UNAUTHENTICATED
          examples:
            GENERIC_401_UNAUTHENTICATED:
              description: Request cannot be authenticated and a new authentication is required
              value:
                status: 401
                code: UNAUTHENTICATED
                message: Request not authenticated due to missing, invalid, or expired credentials. A new authentication is required.
  headers:
    x-correlator:
      description: Correlation id for the different services
      schema:
        $ref: '#/components/schemas/XCorrelator'
  parameters:
    x-correlator:
      name: x-correlator
      in: header
      description: Correlation id for the different services
      schema:
        $ref: '#/components/schemas/XCorrelator'
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
    notificationsBearerAuth:
      type: http
      scheme: bearer
      bearerFormat: '{$request.body#/sinkCredential.credentialType}'
externalDocs:
  description: Product documentation at Camara
  url: https://github.com/camaraproject/CarrierBillingCheckOut
