openapi: 3.2.0
info:
  title: Get Device Identifiers API
  version: 0.3.0
  description: '# Summary


    The Mobile Device Identifier API returns details of the physical mobile device currently being used by a specified mobile subscriber.'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-camara-commonalities: 0.6
servers:
- url: '{apiRoot}/device-identifier/v0.3'
  variables:
    apiRoot:
      default: http://localhost:9091
      description: API root, defined by the service provider, e.g. `api.example.com` or `api.example.com/somepath`
tags:
- name: Get Device Identifiers
  description: Retrieve details about the device being used by a mobile subscriber
paths:
  /retrieve-identifier:
    post:
      summary: Get details about the specific device being used by a given mobile subscriber
      operationId: retrieveIdentifier
      tags:
      - Get Device Identifiers
      security:
      - openId:
        - device-identifier:retrieve-identifier
      parameters:
      - $ref: '#/components/parameters/x-correlator'
      requestBody:
        description: Parameters to create a new session
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBody'
            examples:
              Identify Device By 3-Legged Access Token:
                $ref: '#/components/examples/IdentifyDeviceBy3LeggedToken'
              Identify Device By Phone Number:
                $ref: '#/components/examples/IdentifyDeviceByPhoneNumber'
              Identify Device By IP Address:
                $ref: '#/components/examples/IdentifyDeviceByIPAddress'
              Identify Device By Multiple Identifiers:
                $ref: '#/components/examples/IdentifyDeviceByMultipleIdentifiers'
      responses:
        '200':
          $ref: '#/components/responses/200RetrieveIdentifier'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '422':
          $ref: '#/components/responses/422UnprocessableContent'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
  /retrieve-type:
    post:
      summary: Get details about the type of device being used by a given mobile subscriber
      operationId: retrieveType
      tags:
      - Get Device Identifiers
      security:
      - openId:
        - device-identifier:retrieve-type
      parameters:
      - $ref: '#/components/parameters/x-correlator'
      requestBody:
        description: Parameters to create a new session
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBody'
            examples:
              Identify Device By 3-Legged Access Token:
                $ref: '#/components/examples/IdentifyDeviceBy3LeggedToken'
              Identify Device By Phone Number:
                $ref: '#/components/examples/IdentifyDeviceByPhoneNumber'
              Identify Device By IP Address:
                $ref: '#/components/examples/IdentifyDeviceByIPAddress'
              Identify Device By Multiple Identifiers:
                $ref: '#/components/examples/IdentifyDeviceByMultipleIdentifiers'
      responses:
        '200':
          $ref: '#/components/responses/200RetrieveType'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '422':
          $ref: '#/components/responses/422UnprocessableContent'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
  /retrieve-ppid:
    post:
      summary: Get a pseudonymous identifier for device being used by a given mobile subscriber
      operationId: retrievePPID
      tags:
      - Get Device Identifiers
      security:
      - openId:
        - device-identifier:retrieve-ppid
      parameters:
      - $ref: '#/components/parameters/x-correlator'
      requestBody:
        description: Parameters to identify the mobile subscription when a 2-legged access token is being used
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBody'
            examples:
              Identify Device By 3-Legged Access Token:
                $ref: '#/components/examples/IdentifyDeviceBy3LeggedToken'
              Identify Device By Phone Number:
                $ref: '#/components/examples/IdentifyDeviceByPhoneNumber'
              Identify Device By IP Address:
                $ref: '#/components/examples/IdentifyDeviceByIPAddress'
              Identify Device By Multiple Identifiers:
                $ref: '#/components/examples/IdentifyDeviceByMultipleIdentifiers'
      responses:
        '200':
          $ref: '#/components/responses/200RetrievePPID'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '422':
          $ref: '#/components/responses/422UnprocessableContent'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
components:
  schemas:
    DevicePPID:
      description: 'The individual physical mobile device identifier, expressed as a PPID (Pairwise Pseudonymous Identifier)

        '
      type: object
      properties:
        ppid:
          type: string
          description: A PPID for the identified physical device
          example: b083f65ccdad365d7489fff24b6d5074b30c12b6d81db3404d25964ffd908813
    NetworkAccessIdentifier:
      description: A public identifier addressing a subscription in a mobile network. In 3GPP terminology, it corresponds to the GPSI formatted with the External Identifier ({Local Identifier}@{Domain Identifier}). Unlike the telephone number, the network access identifier is not subjected to portability ruling in force, and is individually managed by each operator.
      type: string
      example: 123456789@domain.com
    ErrorInfo:
      type: object
      required:
      - status
      - code
      - message
      properties:
        status:
          type: integer
          description: HTTP response status code
        code:
          type: string
          description: A human-readable code to describe the error
        message:
          type: string
          description: A human-readable description of what the event represents
    DeviceIdentifier:
      description: 'The individual physical mobile device identifier, as expressed by the IMEI and IMEISV

        '
      type: object
      properties:
        imeisv:
          type: string
          description: IMEISV of the device
          example: '49015420323751800'
        imei:
          type: string
          description: IMEI of the device
          example: '4901542032375181'
    DeviceType:
      description: 'The physical device type, as expressed by Type Approval Code, manufacturer name and model name

        '
      type: object
      properties:
        tac:
          type: string
          description: IMEI TAC of the device
          example: '49015420'
        model:
          type: string
          description: Model of the device
          example: '3110'
        manufacturer:
          type: string
          description: Manufacturer of the device
          example: Nokia
    DeviceResponse:
      description: 'An identifier for the end-user equipment able to connect to the network that the response refers to. This parameter is only returned when the API consumer includes the `device` parameter in their request (i.e. they are using a two-legged access token), and is relevant when more than one device identifier is specified, as only one of those device identifiers is allowed in the response.


        If the API consumer provides more than one device identifier in their request, the API provider must return a single identifier which is the one they are using to fulfil the request, even if the identifiers do not match the same device. API provider does not perform any logic to validate/correlate that the indicated device identifiers match the same device. No error should be returned if the identifiers are otherwise valid to prevent API consumers correlating different identifiers with a given end user.

        '
      allOf:
      - $ref: '#/components/schemas/Device'
      - maxProperties: 1
    CommonResponseBody:
      description: 'Common parameters to be included in all responses

        '
      properties:
        device:
          description: The device subscription identifier that was used to identify the device whose identifier is being returned. If this property is not present, then the device subscription identifier specified in the request was used.
          allOf:
          - $ref: '#/components/schemas/DeviceResponse'
          - example:
              phoneNumber: '+123456789'
        lastChecked:
          description: 'Date and time that the information was last confirmed by the mobile operator to be correct. It must follow [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) and must have time zone.

            '
          type: string
          format: date-time
          example: '2024-02-20T10:41:38.657Z'
    DeviceIpv6Address:
      description: 'The device should be identified by the observed IPv6 address, or by any single IPv6 address from within the subnet allocated to the device (e.g. adding ::0 to the /64 prefix).

        '
      type: string
      format: ipv6
      example: 2001:db8:85a3:8d3:1319:8a2e:370:7344
    DeviceIpv4Addr:
      type: object
      description: 'The device should be identified by either the public (observed) IP address and port as seen by the application server, or the private (local) and any public (observed) IP addresses in use by the device (this information can be obtained by various means, for example from some DNS servers).


        If the allocated and observed IP addresses are the same (i.e. NAT is not in use) then  the same address should be specified for both publicAddress and privateAddress.


        If NAT64 is in use, the device should be identified by its publicAddress and publicPort, or separately by its allocated IPv6 address (field ipv6Address of the Device object)


        In all cases, publicAddress must be specified, along with at least one of either privateAddress or publicPort, dependent upon which is known. In general, mobile devices cannot be identified by their public IPv4 address alone.

        '
      properties:
        publicAddress:
          $ref: '#/components/schemas/SingleIpv4Addr'
        privateAddress:
          $ref: '#/components/schemas/SingleIpv4Addr'
        publicPort:
          $ref: '#/components/schemas/Port'
      anyOf:
      - required:
        - publicAddress
        - privateAddress
      - required:
        - publicAddress
        - publicPort
      example:
        publicAddress: 84.125.93.10
        publicPort: 59765
    XCorrelator:
      type: string
      pattern: ^[a-zA-Z0-9-_:;.\/<>{}]{0,256}$
      example: b4333c46-49c0-4f62-80d7-f0ef930f1c46
    RequestBody:
      description: Common request body to allow optional Device object to be passed
      type: object
      properties:
        device:
          $ref: '#/components/schemas/Device'
    PhoneNumber:
      description: A public identifier addressing a telephone subscription. In mobile networks it corresponds to the MSISDN (Mobile Station International Subscriber Directory Number). In order to be globally unique it has to be formatted in international format, according to E.164 standard, prefixed with '+'.
      type: string
      pattern: ^\+[1-9][0-9]{4,14}$
      example: '+123456789'
    SingleIpv4Addr:
      description: A single IPv4 address with no subnet mask
      type: string
      format: ipv4
      example: 84.125.93.10
    Port:
      description: TCP or UDP port number
      type: integer
      minimum: 0
      maximum: 65535
    Device:
      description: 'End-user equipment able to connect to a mobile network. Examples of devices include smartphones or IoT sensors/actuators.

        The developer can choose to provide the below specified device identifiers:

        * `ipv4Address`

        * `ipv6Address`

        * `phoneNumber`

        * `networkAccessIdentifier`

        NOTE 1: The MNO might support only a subset of these options. The API invoker can provide multiple identifiers to be compatible across different MNOs. In this case the identifiers MUST belong to the same device.

        NOTE 2: For the current Commonalities release, we are enforcing that the networkAccessIdentifier is only part of the schema for future-proofing, and CAMARA does not currently allow its use. After the CAMARA meta-release work is concluded and the relevant issues are resolved, its use will need to be explicitly documented in the guidelines.

        '
      type: object
      properties:
        phoneNumber:
          $ref: '#/components/schemas/PhoneNumber'
        networkAccessIdentifier:
          $ref: '#/components/schemas/NetworkAccessIdentifier'
        ipv4Address:
          $ref: '#/components/schemas/DeviceIpv4Addr'
        ipv6Address:
          $ref: '#/components/schemas/DeviceIpv6Address'
      minProperties: 1
  examples:
    IdentifyDeviceByMultipleIdentifiers:
      description: Identifying device by multiple device identifiers
      value:
        device:
          phoneNumber: '+123456789'
          ipv4Address:
            publicAddress: 84.125.93.10
            publicPort: 59765
          networkAccessIdentifier: 123456789@domain.com
    IdentifyDeviceByPhoneNumber:
      description: Identifying device by phone number
      value:
        device:
          phoneNumber: '+123456789'
    IdentifyDeviceBy3LeggedToken:
      description: Empty JSON when device is identified by access token
      value: {}
    IdentifyDeviceByIPAddress:
      description: Identifying device by IP address
      value:
        device:
          ipv4Address:
            publicAddress: 84.125.93.10
            publicPort: 59765
  responses:
    403Forbidden:
      description: Forbidden
      headers:
        x-correlator:
          $ref: '#/components/headers/X-Correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 403
                code:
                  enum:
                  - PERMISSION_DENIED
          examples:
            Permision Denied:
              description: Permission denied. OAuth2 token access does not have the required scope or when the user fails operational security
              value:
                status: 403
                code: PERMISSION_DENIED
                message: Client does not have sufficient permissions to perform this action.
    401Unauthorized:
      description: Unauthorized
      headers:
        x-correlator:
          $ref: '#/components/headers/X-Correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 401
                code:
                  enum:
                  - UNAUTHENTICATED
          examples:
            Unauthenticated Request:
              description: Request cannot be authenticated and a new authentication is required
              value:
                status: 401
                code: UNAUTHENTICATED
                message: Request not authenticated due to missing, invalid, or expired credentials. A new authentication is required.
    200RetrieveIdentifier:
      description: An device identifier has been found for the specified subscriber
      headers:
        x-correlator:
          $ref: '#/components/headers/X-Correlator'
      content:
        application/json:
          schema:
            required:
            - lastChecked
            - imei
            allOf:
            - $ref: '#/components/schemas/CommonResponseBody'
            - $ref: '#/components/schemas/DeviceIdentifier'
            - $ref: '#/components/schemas/DeviceType'
          examples:
            Successful Identifier Retrieval:
              description: Device identifier has been successfully retrieved when the device subscription was identified by a 3-legged access token or single device subscription identifier
              value:
                lastChecked: '2024-02-20T10:41:38.657Z'
                imeisv: '49015420323751800'
                imei: '4901542032375181'
                tac: '49015420'
                model: '3110'
                manufacturer: Nokia
            Successful Identifier Retrieval With Device Disambiguation:
              description: Device identifier has been successfully retrieved when a 2-legged access token and multiple device subscription identifiers were provided
              value:
                device:
                  phoneNumber: '+123456789'
                lastChecked: '2024-02-20T10:41:38.657Z'
                imeisv: '49015420323751800'
                imei: '4901542032375181'
                tac: '49015420'
                model: '3110'
                manufacturer: Nokia
    400BadRequest:
      description: Bad Request
      headers:
        x-correlator:
          $ref: '#/components/headers/X-Correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 400
                code:
                  enum:
                  - INVALID_ARGUMENT
                  - OUT_OF_RANGE
          examples:
            Insufficient Parameters:
              description: Sufficient parameters must be provided to allow the target UE to be identified
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: At least one of phoneNumber, networkAccessIdentifier, ipv4Address and ipv6Address must be specified
            Inconsistent Device Properties:
              description: Device parameters provided identify different devices
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: Multiple inconsistent device parameters specified
            Invalid Network Access Identifier:
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: 'Invalid format: networkAccessIdentifier'
            Invalid Phone Number:
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: 'Invalid format: phoneNumber'
            Invalid IPv4 Address:
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: 'Invalid format: ipv4Address'
            Invalid IPv6 Address:
              value:
                status: 400
                code: INVALID_ARGUMENT
                message: 'Invalid format: ipv6Address'
            Invalid Port Value:
              value:
                status: 400
                code: OUT_OF_RANGE
                message: 'Invalid value: ipv4Address.publicPort'
    422UnprocessableContent:
      description: Unprocessable Content
      headers:
        x-correlator:
          $ref: '#/components/headers/X-Correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 422
                code:
                  enum:
                  - SERVICE_NOT_APPLICABLE
                  - MISSING_IDENTIFIER
                  - UNSUPPORTED_IDENTIFIER
                  - UNNECESSARY_IDENTIFIER
          examples:
            Service Not Applicable For Device:
              description: The service is not applicable for the identified device
              value:
                status: 422
                code: SERVICE_NOT_APPLICABLE
                message: The service is not applicable for the identified device.
            Unsupported Identifier:
              description: None of the provided identifiers is supported by the implementation
              value:
                status: 422
                code: UNSUPPORTED_IDENTIFIER
                message: None of the provided identifiers is supported by the implementation.
            Unnecessary Identifier:
              description: An explicit identifier has been provided for the device when this is already identified by the access token
              value:
                status: 422
                code: UNNECESSARY_IDENTIFIER
                message: An explicit identifier has been provided for the device when this is already identified by the access token
            Missing Identifier:
              description: An identifier is not included in the request and the device cannot be identified from the 2-legged access token
              value:
                status: 422
                code: MISSING_IDENTIFIER
                message: An identifier is not included in the request and the device cannot be identified from the 2-legged access token
    200RetrieveType:
      description: A device identifier has been found for the specified subscriber
      headers:
        x-correlator:
          $ref: '#/components/headers/X-Correlator'
      content:
        application/json:
          schema:
            required:
            - lastChecked
            - tac
            allOf:
            - $ref: '#/components/schemas/CommonResponseBody'
            - $ref: '#/components/schemas/DeviceType'
          examples:
            Successful Type Retrieval:
              description: Device type has been successfully retrieved when the device subcsription was identified by a 3-legged access token or single device subscription identifier
              value:
                lastChecked: '2024-02-20T10:41:38.657Z'
                tac: '49015420'
                model: '3110'
                manufacturer: Nokia
            Successful Type Retrieval With Device Disambiguation:
              description: Device type has been successfully retrieved when a 2-legged access token and multiple device subscription identifiers were provided
              value:
                device:
                  phoneNumber: '+123456789'
                lastChecked: '2024-02-20T10:41:38.657Z'
                tac: '49015420'
                model: '3110'
                manufacturer: Nokia
    404NotFound:
      description: Not found
      headers:
        x-correlator:
          $ref: '#/components/headers/X-Correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 404
                code:
                  enum:
                  - IDENTIFIER_NOT_FOUND
          examples:
            Device Cannot Be Found:
              description: The provided identifier cannot be matched to a device known to the API provider
              value:
                status: 404
                code: IDENTIFIER_NOT_FOUND
                message: The provided identifier cannot be matched to a device.
    429TooManyRequests:
      description: Too Many Requests
      headers:
        x-correlator:
          $ref: '#/components/headers/X-Correlator'
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/ErrorInfo'
            - type: object
              properties:
                status:
                  enum:
                  - 429
                code:
                  enum:
                  - QUOTA_EXCEEDED
                  - TOO_MANY_REQUESTS
          examples:
            Too Many Requests:
              description: Access to the API has been temporarily blocked due to quota or spike arrest limits being reached
              value:
                status: 429
                code: TOO_MANY_REQUESTS
                message: Rate limit reached
            Quota Exceeded:
              description: Request is rejected due to exceeding a business quota limit
              value:
                status: 429
                code: QUOTA_EXCEEDED
                message: Out of resource quota
    200RetrievePPID:
      description: A pseudonymous device identifier has been found for the specified mobile subscriber
      headers:
        x-correlator:
          $ref: '#/components/headers/X-Correlator'
      content:
        application/json:
          schema:
            required:
            - lastChecked
            - ppid
            allOf:
            - $ref: '#/components/schemas/CommonResponseBody'
            - $ref: '#/components/schemas/DevicePPID'
          examples:
            Successful PPID Retrieval:
              description: Device PPID has been successfully retrieved when the device subcsription was identified by a 3-legged access token or single device subscription identifier
              value:
                lastChecked: '2024-02-20T10:41:38.657Z'
                ppid: b083f65ccdad365d7489fff24b6d5074b30c12b6d81db3404d25964ffd908813
            Successful PPID Retrieval With Device Disambiguation:
              description: Device PPID has been successfully retrieved when a 2-legged access token and multiple device subscription identifiers were provided
              value:
                device:
                  phoneNumber: '+123456789'
                lastChecked: '2024-02-20T10:41:38.657Z'
                ppid: b083f65ccdad365d7489fff24b6d5074b30c12b6d81db3404d25964ffd908813
  headers:
    X-Correlator:
      description: Correlation id for the different services
      required: false
      schema:
        $ref: '#/components/schemas/XCorrelator'
  parameters:
    x-correlator:
      name: x-correlator
      in: header
      description: Correlation id for the different services
      schema:
        $ref: '#/components/schemas/XCorrelator'
  securitySchemes:
    openId:
      description: Common security scheme for all CAMARA APIs
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
externalDocs:
  description: Product documentation at CAMARA
  url: https://github.com/camaraproject/DeviceIdentifier
